/*
  Warnings:

  - You are about to drop the column `uid` on the `Tagged` table. All the data in the column will be lost.
  - Added the required column `idnum` to the `Tagged` table without a default value. This is not possible if the table is not empty.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_Tagged" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "idnum" INT4 NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "url" STRING NOT NULL,
    "tag" STRING NOT NULL,

    CONSTRAINT "Tagged_pkey" PRIMARY KEY ("id")
);
DROP INDEX "Tagged_id_key" CASCADE;
INSERT INTO "_prisma_new_Tagged" ("createdAt","id","tag","url") SELECT "createdAt","id","tag","url" FROM "Tagged";
DROP TABLE "Tagged" CASCADE;
ALTER TABLE "_prisma_new_Tagged" RENAME TO "Tagged";
