-- CreateTable
CREATE TABLE "Untagged" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "url" STRING NOT NULL,
    "tagLeft" STRING,
    "tagRight" STRING,
    "tagUp" STRING,
    "tagDown" STRING,

    CONSTRAINT "Untagged_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Tagged" (
    "id" INT4 NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "url" STRING NOT NULL,
    "tag" STRING NOT NULL,

    CONSTRAINT "Tagged_pkey" PRIMARY KEY ("id")
);
